---
apiVersion: stunner.l7mp.io/v1alpha1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: stunner-prod
spec:
  realm: stunner.l7mp.io
  authType: ephemeral
  AuthRef: ephemeral-secret
